# Generated by Django 4.1.4 on 2024-11-14 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_by",
                    models.UUIDField(db_column="created_by", editable=False, null=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_column="modified_at", null=True
                    ),
                ),
                (
                    "modified_by",
                    models.UUIDField(
                        db_column="modified_by", editable=False, null=True
                    ),
                ),
                ("deleted_at", models.DateTimeField(db_column="deleted_at", null=True)),
                (
                    "deleted_by",
                    models.UUIDField(db_column="deleted_by", editable=False, null=True),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={"db_table": "rol",},
        ),
        migrations.CreateModel(
            name="UserRol",
            fields=[
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_by",
                    models.UUIDField(db_column="created_by", editable=False, null=True),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, db_column="modified_at", null=True
                    ),
                ),
                (
                    "modified_by",
                    models.UUIDField(
                        db_column="modified_by", editable=False, null=True
                    ),
                ),
                ("deleted_at", models.DateTimeField(db_column="deleted_at", null=True)),
                (
                    "deleted_by",
                    models.UUIDField(db_column="deleted_by", editable=False, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="security.rol"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "user_rol",},
        ),
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
