# Generated by Django 4.1.4 on 2024-11-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0002_rol_userrol_authtoken"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="data_joined",),
    ]
