# Generated by Django 4.1.4 on 2024-11-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
