# Generated by Django 4.1.4 on 2024-11-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_management", "0002_event_is_featured"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["date"],
                "permissions": [
                    ("create_event", "Can create event"),
                    ("edit_event", "Can edit event"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["reservation_date"],
                "permissions": [("manage_reservations", "Can manage reservations")],
            },
        ),
    ]
