# Generated by Django 4.1.4 on 2024-11-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_management", "0004_alter_reservation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="total_slots",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
