name: Run Tests with Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests and Generate Coverage Report
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: ${{ secrets.CONFIG_SETTINGS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      CSRF_TRUSTED_ORIGINS:  ${{ secrets.ALLOWED_HOSTS }}
      CORS_ALLOWED_ORIGINS:  ${{ secrets.CORS_ALLOWED_ORIGINS }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt

      - name: Run Tests with Coverage
        run: |
          cd src
          coverage run -m pytest --ds=config.settings.settings_test --disable-warnings
          coverage report -m
